Social Distance Checker
marsiitr/Social-Distance-Checker pull request #1
Opened 2021-08-06 18:17 UTC by rahulgrandhi13579

2021-08-07 08:05 UTC, theobscuredev requested changes
Hey @rahulgrandhi13579 

Few changes are required!!!!

1. Update the README file. Refer the Documentation Guidelines for the same. While you prepare the README, make sure you consider the image aligning and text justification using appropriate tags. Refer this README for more info: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md
2. Update the name of the 'Poster and Report'. 'Images and Videos', 'Images' etc folders. Make sure all the directories are named as per the convention mentioned in the guidelines.
3. Also, update the name of all the files. Avoid naming them as 'IMG_20210806_221926.jpg'. Naming should be self-explanatory and should justify the content present within.
4. Update the project report. Add a section for mentors and elaborate a few slides.
5. Try to have a uniform naming convention for the files. Either use CamelCase (For eg: CentroidTracker.py or centroidTracker.py)/ use underscores (centroid_tracker.py)/ use hyphens (centroid-tracker.py) but make sure it's uniform throughout the entire codebase.

2021-08-07 11:12 UTC, theobscuredev commented
@rahulgrandhi13579 Lemme know once you've made the final changes. Make sure to tag me (@) in this thread.

2021-08-07 16:58 UTC, rahulgrandhi13579 commented
Sir, we have made the necessary changes that you have stated . So once
could you please check them whether they are correct or do we need to do
any other changes.

On Sat, Aug 7, 2021 at 4:43 PM Pradnesh Chavan ***@***.***>
wrote:

> @rahulgrandhi13579 <https://github.com/rahulgrandhi13579> Lemme know once
> you've made the final changes. Make sure to tag me (@) in this thread.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#issuecomment-894640885>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVDTXVPGMI2EKDEMY6CC2XTT3UIMFANCNFSM5BWMCUCQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-07 18:08 UTC, theobscuredev requested changes
Hey @rahulgrandhi13579 & team;
Nice work however lots of changes still have to be made:

1. Capitalize 'i' and 'v' while naming the 'Images and Videos', 'Images' and 'Videos' directories. 
2. Update the README file as per the changes suggested. Try to elaborate your algorithm using code snippets/flowcharts. For eg: https://github.com/brahatesh/RoverSim#software-aspects. If need arises, you can create a new README and include it inside the src folder. Make sure others can understand the code logic by referring the README file which isn't clear currently.

2021-08-07 18:08 UTC, theobscuredev commented on README.md
>  Open Projects 2021
Apply header using: '## Open Projects 2021'

2021-08-07 18:08 UTC, theobscuredev commented on README.md
>  # Social-Distance-Checker
~~Social-Distance-Checker~~ -> Social Distance Checker

2021-08-07 18:08 UTC, theobscuredev commented on README.md
> +![socialdistancing_mask_detection](https://user-images.githubusercontent.com/88554453/128603773-dceafea5-7f4f-46a8-8303-98dc23235368.jpg)
Center align all the images using the `<p>` paragraph tag and `align` attribute. For eg:
`<p align="center">`
  `<img src="https://github.com........." alt="LED Matrix">`
  `<i>LED Matrix</i>`
`</p>`

Also resize the images by assigning the dimensions and add title for each pic. Refer this README for more info: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md

2021-08-07 18:08 UTC, theobscuredev commented on README.md
> +
Insert a 'Software Aspect' heading and elaborate your algorithm. If it's taking up too much space or if it's too elaborate, you can also create a separate README for the same. For eg: https://github.com/brahatesh/RoverSim#software-aspects
Make sure you're able to explain the logic of the algorithm in the context of the code written. Flowcharts or code snippets can be used for explanation.

2021-08-07 18:08 UTC, theobscuredev commented on README.md
> +It is used to maintain social distancing and helps in preventing the spread of deadly communicable diseases.
Elaborate your project applications. Consider all the aspects like how exactly people can use the features in your app to 'Prevent the spread of the virus'.

2021-08-07 18:08 UTC, theobscuredev commented on README.md
> +1.) It fails to detect the persons when the video of one of person gets blocked by another person.
Use proper bullet points. Remove the unnecessary fullstop after each digit.

2021-08-07 18:08 UTC, theobscuredev commented on README.md
> +3.) Annushree
Hyperlink the Github ID of each team member & your mentors. Refer this README: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md

2021-08-07 18:08 UTC, theobscuredev commented on README.md
> +2.) https://youtu.be/Ax6P93r32KU
Hyperlink the references properly. Mention the title for each reference and just include the URL in the hyperlink. Refer this README for more info: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md

2021-08-07 18:08 UTC, theobscuredev commented on README.md
> +The social distance checker is an opencv project in which we monitor the distances between the people and if the distance comes out to be less than the threshold value (calibrated six feet in terms o
Justify the entire text using the `<p>` paragraph tag and `justify` attribute. Make sure you justify all the paragraphs separately. For eg:
`<p align="justify">`
  `<h2>Abstract</h2>`
  `<p>A Rube Goldberg Machine is .........................</p>`
`</p>`

Refer this README for the same: https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md

2021-08-07 18:08 UTC, theobscuredev commented on README.md
> +# Application
Include a tabulated cost structure depicting the price of any paid software used before the Applications. For eg: https://github.com/marsiitr/IoT-ChatBot#cost-structure

2021-08-09 12:33 UTC, rahulgrandhi13579 commented
Sir, we have made all the necessary changes that you have stated . Are
these correct or need any further changes?

On Sat, Aug 7, 2021 at 11:38 PM Pradnesh Chavan ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey @rahulgrandhi13579 <https://github.com/rahulgrandhi13579> & team;
> Nice work however lots of changes still have to be made:
>
>    1. Capitalize 'i' and 'v' while naming the 'Images and Videos',
>    'Images' and 'Videos' directories.
>    2. Update the README file as per the changes suggested. Try to
>    elaborate your algorithm using code snippets/flowcharts. For eg:
>    https://github.com/brahatesh/RoverSim#software-aspects. If need
>    arises, you can create a new README and include it inside the src folder.
>    Make sure others can understand the code logic by referring the README file
>    which isn't clear currently.
>
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#discussion_r684660385>
> :
>
> > @@ -1,2 +1,65 @@
>  # Social-Distance-Checker
>  Open Projects 2021
>
> Apply header using: '## Open Projects 2021'
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#discussion_r684660467>
> :
>
> > @@ -1,2 +1,65 @@
>  # Social-Distance-Checker
>
> Social-Distance-Checker -> Social Distance Checker
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#discussion_r684660545>
> :
>
> > @@ -1,2 +1,65 @@
>  # Social-Distance-Checker
>  Open Projects 2021
> +
> +
> +![socialdistancing_mask_detection](https://user-images.githubusercontent.com/88554453/128603773-dceafea5-7f4f-46a8-8303-98dc23235368.jpg)
>
> Center align all the images using the <p> paragraph tag and align
> attribute. For eg:
> <p align="center">
> <img src="https://github.com........." alt="LED Matrix">
> <i>LED Matrix</i>
> </p>
>
> Also resize the images by assigning the dimensions and add title for each
> pic. Refer this README for more info:
> https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#discussion_r684660936>
> :
>
> > +
> +![socialdistancing_mask_detection](https://user-images.githubusercontent.com/88554453/128603773-dceafea5-7f4f-46a8-8303-98dc23235368.jpg)
> +
> +# Abstract
> +
> +The social distance checker is an opencv project in which we monitor the distances between the people and if the distance comes out to be less than the threshold value (calibrated six feet in terms of pixels) then we indicate the violation by surrounding them with a red bounding box and with the help of AI/ML/pretrained files , if the person does not wear a mask then his face gets surrounded by a red bounding box.
> +
> +# Motivation
> +
> +The Outbreak of COVID-19 has affected almost everyone across the globe. During this pandemic, people are
> +advised not to be in close contact with others to reduce the spread of the disease, but due to the negligence
> +of many, we continue to face the repercussions of this pandemic
> +As the name suggests, social distancing implies that people should physically distance themselves from
> +one another, reducing the spread of contagious diseases like COVID. So, in order to monitor if people are
> +maintaining social distance or not, we are working on the project named, Social distance checker.
> +
>
> Insert a 'Software Aspect' heading and elaborate your algorithm. If it's
> taking up too much space or if it's too elaborate, you can also create a
> separate README for the same. For eg:
> https://github.com/brahatesh/RoverSim#software-aspects
> Make sure you're able to explain the logic of the algorithm in the context
> of the code written. Flowcharts or code snippets can be used for
> explanation.
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#discussion_r684661070>
> :
>
> > +# Application
> +
> +It is used to maintain social distancing and helps in preventing the spread of deadly communicable diseases.
>
> Elaborate your project applications. Consider all the aspects like how
> exactly people can use the features in your app to 'Prevent the spread of
> the virus'.
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#discussion_r684661147>
> :
>
> > +# Motivation
> +
> +The Outbreak of COVID-19 has affected almost everyone across the globe. During this pandemic, people are
> +advised not to be in close contact with others to reduce the spread of the disease, but due to the negligence
> +of many, we continue to face the repercussions of this pandemic
> +As the name suggests, social distancing implies that people should physically distance themselves from
> +one another, reducing the spread of contagious diseases like COVID. So, in order to monitor if people are
> +maintaining social distance or not, we are working on the project named, Social distance checker.
> +
> +# Application
> +
> +It is used to maintain social distancing and helps in preventing the spread of deadly communicable diseases.
> +
> +# Limitations
> +
> +1.) It fails to detect the persons when the video of one of person gets blocked by another person.
>
> Use proper bullet points. Remove the unnecessary fullstop after each digit.
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#discussion_r684661250>
> :
>
> > +# Team members
> +
> +1.) Alok Kohli
> +
> +2.) Grandhi Rahul Gupta
> +
> +3.) Prem Chhangani
> +
> +4.) Pallapu Sree Prudhveenadh
> +
> +5.) Vansh Mehra
> +
> +# Mentors
> +
> +1.) Agrim Aggarwal
> +
> +2.) Anfal Ansari
> +
> +3.) Annushree
>
> Hyperlink the Github ID of each team member & your mentors. Refer this
> README:
> https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#discussion_r684661260>
> :
>
> > +# References
> +
> +1.) https://youtu.be/UM9oDhhAg88
> +
> +2.) https://youtu.be/Ax6P93r32KU
>
> Hyperlink the references properly. Mention the title for each reference
> and just include the URL in the hyperlink. Refer this README for more info:
> https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#discussion_r684661319>
> :
>
> > +# Abstract
> +
> +The social distance checker is an opencv project in which we monitor the distances between the people and if the distance comes out to be less than the threshold value (calibrated six feet in terms of pixels) then we indicate the violation by surrounding them with a red bounding box and with the help of AI/ML/pretrained files , if the person does not wear a mask then his face gets surrounded by a red bounding box.
>
> Justify the entire text using the <p> paragraph tag and justify
> attribute. Make sure you justify all the paragraphs separately. For eg:
> <p align="justify">
> <h2>Abstract</h2>
> <p>A Rube Goldberg Machine is .........................</p>
> </p>
>
> Refer this README for the same:
> https://raw.githubusercontent.com/marsiitr/Rube-Goldberg-Machine/master/README.md
> ------------------------------
>
> In README.md
> <https://github.com/marsiitr/Social-Distance-Checker/pull/1#discussion_r684661458>
> :
>
> > +![socialdistancing_mask_detection](https://user-images.githubusercontent.com/88554453/128603773-dceafea5-7f4f-46a8-8303-98dc23235368.jpg)
> +
> +# Abstract
> +
> +The social distance checker is an opencv project in which we monitor the distances between the people and if the distance comes out to be less than the threshold value (calibrated six feet in terms of pixels) then we indicat [...]

2021-08-09 17:05 UTC, SanjeevKrishnan approved these changes
Good work team!
Merging the PR

2021-08-09 17:05 UTC, merged